/**
 * WORKFLOW EXECUTION TYPE DEFINITIONS
 * ====================================
 * TypeScript types for the agentic workflow transparency system.
 * These types model the 8-phase workflow pipeline (A0-A9) that generates
 * compliance tasks from regulatory obligations.
 */

/**
 * The 8-phase workflow pipeline identifiers
 */
export type WorkflowPhaseId =
  | 'A0'  // Deal Profiler
  | 'A1'  // Obligation Extractor
  | 'A2'  // Risk Mapper
  | 'A3'  // Control Designer
  | 'A4'  // Schema Designer
  | 'A6'  // Policy Generator
  | 'A7'  // Unit Tester
  | 'A8'  // Dry-Run
  | 'A9'  // Publisher

/**
 * Overall workflow execution status
 */
export type WorkflowStatus =
  | 'COMPLETED'       // All phases successful
  | 'RUNNING'         // Currently executing
  | 'PENDING_HITL'    // Waiting for human approval
  | 'FAILED'          // Error occurred
  | 'CANCELLED'       // User cancelled

/**
 * Human-in-the-loop gate approval status
 */
export type HITLStatus =
  | 'APPROVED'        // Human approved, continue
  | 'REJECTED'        // Human rejected, stop workflow
  | 'PENDING'         // Waiting for human decision
  | 'SKIPPED'         // Gate skipped (optional gate)

/**
 * Phase execution status
 */
export type PhaseStatus =
  | 'COMPLETED'
  | 'RUNNING'
  | 'PENDING'
  | 'FAILED'
  | 'SKIPPED'

/**
 * Quality check metrics for LLM outputs
 */
export interface QualityCheck {
  ragas_faithfulness?: number      // 0.0-1.0 score from RAGAS framework
  ragas_answer_relevancy?: number  // 0.0-1.0 score
  source_citations?: string        // e.g., "8/8 obligations cited"
  validation_passed?: boolean      // Schema validation result
  error_count?: number             // Number of validation errors
  warning_count?: number           // Number of warnings
}

/**
 * Human-in-the-loop approval gate
 */
export interface HITLGate {
  status: HITLStatus
  approver?: string                // User who approved/rejected
  approved_at?: string             // ISO 8601 timestamp
  rejected_at?: string             // ISO 8601 timestamp
  rejection_reason?: string        // Why it was rejected
  feedback?: string                // Additional human feedback
}

/**
 * Data source metadata for a phase
 */
export interface DataSource {
  type: 'qatar-unified-obligations' | 'graphiti' | 'web-scrape' | 'llm-generation'
  source_name?: string             // e.g., "AAOIFI SS-9", "QCB Law 13/2012"
  confidence_score?: number        // 0.0-1.0
  timestamp?: string               // When data was retrieved
}

/**
 * Single obligation extracted by A1
 */
export interface ExtractedObligation {
  id: string                       // e.g., "UNIFIED-OBL-001"
  title: string
  source: string                   // Citation (e.g., "QCB Law 13/2012 Art 109")
  link?: string                    // Link to Qatar GRC page
  category?: string                // SSB_GOVERNANCE, RISK_MANAGEMENT, etc.
  priority?: 'Critical' | 'High' | 'Medium' | 'Low'
}

/**
 * Single risk identified by A2
 */
export interface IdentifiedRisk {
  id: string                       // e.g., "RISK-001"
  title: string
  description: string
  likelihood: 'High' | 'Medium' | 'Low'
  impact: 'High' | 'Medium' | 'Low'
  mitigation_control?: string      // Control ID that mitigates this
}

/**
 * Single control designed by A3
 */
export interface DesignedControl {
  id: string                       // e.g., "SG-01"
  name: string
  description: string
  type: 'Preventive' | 'Detective' | 'Corrective'
  automation_level?: 'Automated' | 'Semi-Automated' | 'Manual'
  related_obligations: string[]    // Obligation IDs this control addresses
}

/**
 * Schema field designed by A4
 */
export interface SchemaField {
  field_name: string
  field_type: string               // text, date, number, boolean, etc.
  required: boolean
  validation_rule?: string
  help_text?: string
}

/**
 * Test case generated by A7
 */
export interface TestCase {
  id: string
  scenario: string
  expected_result: string
  actual_result?: string
  status?: 'PASSED' | 'FAILED' | 'PENDING'
}

/**
 * A single phase in the workflow execution
 */
export interface WorkflowPhase {
  id: WorkflowPhaseId
  name: string                     // Human-readable name
  status: PhaseStatus
  started_at?: string              // ISO 8601 timestamp
  completed_at?: string            // ISO 8601 timestamp
  duration_seconds?: number

  // Input data for this phase
  input?: Record<string, any>

  // Output data from this phase
  output?: Record<string, any>

  // Optional data source metadata
  data_source?: DataSource

  // Optional quality checks
  quality_checks?: QualityCheck

  // Optional HITL gate (not all phases have one)
  hitl_gate?: HITLGate

  // Error information if phase failed
  error?: {
    message: string
    details?: string
    timestamp: string
  }

  // Warnings (non-fatal issues)
  warnings?: string[]
}

/**
 * Outputs generated by the workflow
 */
export interface WorkflowOutputs {
  guardian_policy?: string         // Filename of generated Guardian policy
  guardian_policy_url?: string     // URL to download/view policy

  tasks_generated: Array<{
    id: string                     // Task ID (e.g., "SG-02")
    title: string
    category?: string
    priority?: string
    status?: string
  }>

  controls_activated: number       // Number of controls activated
  controls_list?: string[]         // List of control IDs

  obligations_addressed: number    // Number of obligations covered
  obligations_list?: string[]      // List of obligation IDs

  risks_identified?: number
  test_cases_generated?: number
  validation_errors?: number
}

/**
 * Complete workflow execution record
 */
export interface WorkflowExecution {
  // Core identification
  id: string                       // e.g., "wf-20241108-001"
  name: string                     // Human-readable name
  deal_id?: string                 // Associated deal ID
  deal_name?: string               // Deal name for display

  // Execution metadata
  status: WorkflowStatus
  created_at: string               // ISO 8601 timestamp
  started_at?: string
  completed_at?: string
  duration_seconds?: number

  // User who initiated
  initiated_by?: string            // User name or ID

  // All 8 phases
  phases: WorkflowPhase[]

  // Final outputs
  outputs: WorkflowOutputs

  // Overall quality metrics
  overall_quality?: {
    avg_faithfulness?: number
    total_citations?: number
    validation_errors?: number
    hitl_approvals?: number
  }

  // Optional tags for filtering
  tags?: string[]
}

/**
 * Filter options for workflow execution list
 */
export interface WorkflowExecutionFilters {
  status?: WorkflowStatus[]
  deal_id?: string
  date_from?: string
  date_to?: string
  initiated_by?: string
  tags?: string[]
}

/**
 * Task lineage information - shows how a task was created
 */
export interface TaskLineage {
  task_id: string
  task_title: string

  // The workflow that created this task
  workflow_execution_id: string
  workflow_name: string

  // The obligation that triggered this task
  source_obligation?: ExtractedObligation

  // The control that implements this task
  implementing_control?: DesignedControl

  // The risk this task mitigates
  mitigating_risk?: IdentifiedRisk

  // Which phase created this task
  created_by_phase: WorkflowPhaseId
  created_at: string
}
