import type { ParsedDocument } from '../types/digitization'

/**
 * MOCK PARSED DOCUMENT
 * ====================
 * Simulates LlamaParse output for IIFM Mudarabah Standard (ST-14).
 *
 * In production, this would be generated by LlamaParse API from uploaded PDF.
 */

export const mockParsedDocument: ParsedDocument = {
  text: `IIFM Mudarabah Standard (ST-14)

  International Islamic Financial Market

  Standard for Mudarabah Contracts in Islamic Finance

  Version 1.2 | Published: January 2023

  1. INTRODUCTION

  1.1 Scope
  This standard establishes the requirements for Mudarabah contracts in Islamic finance, providing guidance on structure, documentation, profit-sharing mechanisms, and Shariah compliance.

  1.2 Purpose
  To ensure consistency, transparency, and Shariah compliance in Mudarabah partnerships across the Islamic finance industry.

  2. SHARIAH COMPLIANCE CRITERIA

  2.1 Core Principles
  - Profit-sharing ratio must be predetermined and agreed upon
  - Loss is borne exclusively by the capital provider (Rab-ul-Mal)
  - No guaranteed returns or fixed income
  - Investment must comply with Shariah principles

  2.2 Prohibited Activities
  - Investment in riba-based activities
  - Investment in haram industries
  - Speculative activities (gharar/maysir)

  3. ROLES AND RESPONSIBILITIES

  3.1 Rab-ul-Mal (Capital Provider)
  - Provides capital for the investment
  - Bears all financial losses
  - Cannot interfere in day-to-day management

  3.2 Mudarib (Investment Manager)
  - Manages the capital with expertise
  - Bears no financial loss (except misconduct)
  - Entitled to agreed profit share

  3.3 Shariah Board
  - Reviews contract for Shariah compliance
  - Certifies permissible investments
  - Monitors ongoing compliance

  4. PROFIT DISTRIBUTION FRAMEWORK

  4.1 Profit Sharing Ratios
  Profits must be distributed according to predetermined ratios. Common structures include:

  - Conservative: Rab-ul-Mal 70%, Mudarib 30%
  - Moderate: Rab-ul-Mal 60%, Mudarib 40%
  - Aggressive: Rab-ul-Mal 50%, Mudarib 50%

  4.2 Distribution Timing
  - Monthly, quarterly, or annual distribution
  - Final settlement upon contract termination

  5. DOCUMENTATION REQUIREMENTS

  5.1 Contract Elements
  - Identity of parties
  - Capital amount and currency
  - Profit-sharing ratio
  - Investment scope and restrictions
  - Duration and termination clauses

  5.2 Shariah Certification
  - Initial Shariah board approval required
  - Annual compliance audits
  - Certification must be renewed

  6. AUDIT AND REPORTING

  6.1 Financial Reporting
  - Regular profit/loss statements
  - Investment portfolio disclosure
  - Compliance with AAOIFI standards

  6.2 Shariah Audit
  - Independent Shariah audit required
  - Non-compliant activities must be purified

  This is an abbreviated version. Full standard contains 45 pages with detailed provisions.`,
  structure: {
    sections: [
      {
        title: '1. Introduction',
        content:
          'This standard establishes the requirements for Mudarabah contracts in Islamic finance...',
        subsections: [
          {
            title: '1.1 Scope',
            content:
              'This standard establishes the requirements for Mudarabah contracts in Islamic finance, providing guidance on structure, documentation, profit-sharing mechanisms, and Shariah compliance.',
          },
          {
            title: '1.2 Purpose',
            content:
              'To ensure consistency, transparency, and Shariah compliance in Mudarabah partnerships across the Islamic finance industry.',
          },
        ],
      },
      {
        title: '2. Shariah Compliance Criteria',
        content: 'Core principles and prohibited activities...',
        subsections: [
          {
            title: '2.1 Core Principles',
            content:
              'Profit-sharing ratio must be predetermined; Loss borne by capital provider; No guaranteed returns; Shariah-compliant investment',
          },
          {
            title: '2.2 Prohibited Activities',
            content: 'Riba-based activities, haram industries, speculative activities (gharar/maysir)',
          },
        ],
      },
      {
        title: '3. Roles and Responsibilities',
        content: 'Defining stakeholder roles...',
        subsections: [
          {
            title: '3.1 Rab-ul-Mal (Capital Provider)',
            content: 'Provides capital, bears losses, cannot interfere in management',
          },
          {
            title: '3.2 Mudarib (Investment Manager)',
            content: 'Manages capital, bears no financial loss, entitled to profit share',
          },
          {
            title: '3.3 Shariah Board',
            content: 'Reviews contracts, certifies investments, monitors compliance',
          },
        ],
      },
      {
        title: '4. Profit Distribution Framework',
        content: 'Profit sharing structures and timing...',
        subsections: [
          {
            title: '4.1 Profit Sharing Ratios',
            content: 'Predetermined ratios: Conservative (70/30), Moderate (60/40), Aggressive (50/50)',
          },
          {
            title: '4.2 Distribution Timing',
            content: 'Monthly, quarterly, or annual distribution; final settlement upon termination',
          },
        ],
      },
    ],
    tables: [
      {
        title: 'Table 4.1: Profit Distribution Scenarios',
        headers: ['Profit Level', 'Rab-ul-Mal Share', 'Mudarib Share'],
        rows: [
          ['Conservative (< 10% ROI)', '70%', '30%'],
          ['Moderate (10-20% ROI)', '60%', '40%'],
          ['Aggressive (> 20% ROI)', '50%', '50%'],
        ],
      },
      {
        title: 'Table 5.1: Required Documentation',
        headers: ['Document', 'Provider', 'Review Authority'],
        rows: [
          ['Mudarabah Contract', 'Legal Team', 'Shariah Board'],
          ['Capital Contribution Certificate', 'Rab-ul-Mal', 'Auditor'],
          ['Shariah Compliance Certificate', 'Shariah Board', 'Regulator'],
          ['Investment Mandate', 'Mudarib', 'Rab-ul-Mal'],
        ],
      },
    ],
  },
  metadata: {
    pages: 45,
    language: 'en',
    hasFormulas: true,
    hasTables: true,
  },
}
